// ============================================================
// FIREWALL GUARDIAN — Game Configuration
// ============================================================

const CONFIG = {
  // Canvas
  BASE_WIDTH: 1280,
  BASE_HEIGHT: 720,

  // Colors (from plan.md)
  COLORS: {
    BG: '#0a0e27',
    BG_PANEL: 'rgba(26, 30, 58, 0.85)',
    SAFE: '#00ff88',
    WARNING: '#ffaa00',
    DANGER: '#ff2244',
    MALWARE: '#9b30ff',
    PANEL_BORDER: '#00e5ff',
    TEXT_PRIMARY: '#ffffff',
    TEXT_SECONDARY: '#8899aa',
    ACCENT: '#00b4ff',
    DARK_SLATE: '#1a1e3a',
    FIREWALL: '#ff4422',
    RANSOMWARE: '#ff0033',
    GRID: 'rgba(0, 229, 255, 0.06)',
    GRID_LINE: 'rgba(0, 229, 255, 0.12)',
    HEALTH_HIGH: '#00ff88',
    HEALTH_MID: '#ffaa00',
    HEALTH_LOW: '#ff2244',
  },

  SPRITES: {
    NODES: {
      CLOUD: 'assets/sprites/node_cloud.png',
      FIREWALL: 'assets/sprites/node_firewall.png',
      ROUTER: 'assets/sprites/node_router.png',
      SWITCH: 'assets/sprites/node_router.png',
      WEB: 'assets/sprites/node_webserver.png',
      DB: 'assets/sprites/node_dbserver.png',
      MAIL: 'assets/sprites/node_mailserver.png',
      PC: 'assets/sprites/node_pc.png',
      PC1: 'assets/sprites/node_pc.png',
      PC2: 'assets/sprites/node_pc.png',
      PC3: 'assets/sprites/node_pc.png',
    },
    TOOLS: {
      BLOCK_IP: 'assets/sprites/tower_firewall.png',
      QUARANTINE: 'assets/sprites/tower_antivirus.png',
      PATCH: 'assets/sprites/tower_ids.png',
      INSPECT: 'assets/sprites/tower_encryption.png',
      REVOKE_ACCESS: 'assets/sprites/tower_honeypot.png',
      BACKUP_RESTORE: 'assets/sprites/tower_backup.png',
    },
    THREAT: 'assets/sprites/enemy_threat.png',
    ALERT_RING: 'assets/sprites/ui_alert_ring.png',
    PANEL: 'assets/sprites/panel_frame.png',
  },

  // Network node types
  NODE_TYPES: {
    CLOUD: { label: 'Cloud', icon: 'CLOUD', tier: 0 },
    FIREWALL: { label: 'Firewall', icon: 'FIREWALL', tier: 1 },
    ROUTER: { label: 'Router', icon: 'ROUTER', tier: 2 },
    SWITCH: { label: 'Switch', icon: 'SWITCH', tier: 2 },
    WEB: { label: 'Web Server', icon: 'WEB', tier: 3 },
    DB: { label: 'DB Server', icon: 'DB', tier: 3 },
    MAIL: { label: 'Mail Server', icon: 'MAIL', tier: 3 },
    PC1: { label: 'PC-1', icon: 'PC1', tier: 4 },
    PC2: { label: 'PC-2', icon: 'PC2', tier: 4 },
    PC3: { label: 'PC-3', icon: 'PC3', tier: 4 },
  },

  // Network topology (connections)
  TOPOLOGY: [
    ['CLOUD', 'FIREWALL'],
    ['FIREWALL', 'ROUTER'],
    ['ROUTER', 'SWITCH'],
    ['ROUTER', 'WEB'],
    ['SWITCH', 'DB'],
    ['SWITCH', 'MAIL'],
    ['WEB', 'PC1'],
    ['DB', 'PC2'],
    ['MAIL', 'PC3'],
  ],

  // Threat types
  THREATS: {
    PORT_SCAN: {
      name: 'Port Scan',
      color: '#ffaa00',
      speed: 0.4,
      damage: 5,
      defense: 'BLOCK_IP',
      shape: 'radar',
      intel: 'Port scanning is often the first step in a cyberattack. Tools like Nmap are used to discover open ports and services.',
    },
    PHISHING: {
      name: 'Phishing Email',
      color: '#ff8800',
      speed: 0.6,
      damage: 10,
      defense: 'BLOCK_IP',
      shape: 'envelope',
      intel: 'Phishing accounts for 91% of cyberattacks. Always verify sender addresses and never click suspicious links.',
    },
    SQL_INJECTION: {
      name: 'SQL Injection',
      color: '#ff2244',
      speed: 0.8,
      damage: 15,
      defense: 'PATCH',
      shape: 'syringe',
      intel: 'SQL Injection is ranked #3 on the OWASP Top 10. Always use parameterized queries to prevent it.',
    },
    BRUTE_FORCE: {
      name: 'Brute Force',
      color: '#ff4444',
      speed: 0.6,
      damage: 10,
      defense: 'REVOKE_ACCESS',
      shape: 'ram',
      intel: 'Brute force attacks try thousands of password combinations. Rate limiting and account lockout policies prevent this.',
    },
    MALWARE: {
      name: 'Malware',
      color: '#9b30ff',
      speed: 0.8,
      damage: 15,
      defense: 'QUARANTINE',
      shape: 'virus',
      intel: 'Lateral movement means attackers move between systems after gaining initial access. Network segmentation limits this.',
    },
    DATA_EXFIL: {
      name: 'Data Exfiltration',
      color: '#cc0033',
      speed: 0.4,
      damage: 25,
      defense: 'INSPECT',
      shape: 'leak',
      intel: 'Data exfiltration can be hidden inside normal HTTPS traffic. Deep packet inspection helps detect anomalies.',
    },
    RANSOMWARE: {
      name: 'Ransomware',
      color: '#ff0033',
      speed: 1.0,
      damage: 30,
      defense: 'BACKUP_RESTORE',
      shape: 'skull_lock',
      intel: 'Ransomware encrypts files and demands payment. Regular offline backups are your best defense against it.',
    },
  },

  // Defense tools
  TOOLS: {
    BLOCK_IP: { name: 'Block IP', icon: 'shield', key: '1', desc: 'Block traffic from a source IP' },
    QUARANTINE: { name: 'Quarantine', icon: 'cage', key: '2', desc: 'Isolate an infected machine' },
    PATCH: { name: 'Patch', icon: 'wrench', key: '3', desc: 'Fix a vulnerability on a server' },
    INSPECT: { name: 'Decrypt & Inspect', icon: 'magnify', key: '4', desc: 'Deep packet inspection' },
    REVOKE_ACCESS: { name: 'Revoke Access', icon: 'key_x', key: '5', desc: 'Revoke compromised credentials' },
    BACKUP_RESTORE: { name: 'Backup Restore', icon: 'rewind', key: '6', desc: 'Restore from clean backup' },
  },

  // Scoring
  SCORE: {
    CORRECT: 100,
    MISSED: -200,
    FALSE_POSITIVE: -150,
    SPEED_BONUS_THRESHOLD: 2000, // ms — under this gets bonus
    SPEED_BONUS: 50,
    PERFECT_PHASE: 500,
  },

  // Phases (durations in seconds)
  PHASES: [
    {
      id: 1,
      name: 'RECONNAISSANCE',
      duration: 60,
      subtitle: 'Port scans and probes are hitting the firewall...',
      narration: 'PHANTOM CLAW is scanning your network, looking for weaknesses. Block the suspicious traffic before they map your infrastructure.',
      threats: ['PORT_SCAN', 'PORT_SCAN', 'PORT_SCAN', 'PORT_SCAN', 'PORT_SCAN', 'PORT_SCAN', 'PORT_SCAN', 'PORT_SCAN'],
      spawnInterval: 6500,
      isTutorial: true,
    },
    {
      id: 2,
      name: 'INITIAL ACCESS',
      duration: 90,
      subtitle: 'Phishing emails and injection attacks incoming!',
      narration: 'They found openings. Phishing emails are flooding inboxes. SQL injection probes are targeting the web portal. Block every vector.',
      threats: ['PHISHING', 'SQL_INJECTION', 'BRUTE_FORCE', 'PHISHING', 'SQL_INJECTION', 'PORT_SCAN', 'BRUTE_FORCE', 'PHISHING', 'SQL_INJECTION', 'BRUTE_FORCE', 'PHISHING', 'SQL_INJECTION'],
      spawnInterval: 6000,
      isTutorial: false,
    },
    {
      id: 3,
      name: 'LATERAL MOVEMENT',
      duration: 60,
      subtitle: 'Malware spreading through internal network!',
      narration: 'They\'re inside. Malware is spreading between machines. Quarantine infected endpoints and patch vulnerabilities NOW.',
      threats: ['MALWARE', 'MALWARE', 'BRUTE_FORCE', 'MALWARE', 'SQL_INJECTION', 'MALWARE', 'MALWARE', 'BRUTE_FORCE', 'MALWARE'],
      spawnInterval: 5500,
      isTutorial: false,
    },
    {
      id: 4,
      name: 'DATA EXFILTRATION',
      duration: 60,
      subtitle: 'Patient data being siphoned through encrypted tunnels!',
      narration: 'PHANTOM CLAW is extracting patient records disguised as normal HTTPS traffic. Use deep packet inspection to find the hidden data streams.',
      threats: ['DATA_EXFIL', 'DATA_EXFIL', 'MALWARE', 'DATA_EXFIL', 'PHISHING', 'DATA_EXFIL', 'DATA_EXFIL', 'BRUTE_FORCE'],
      spawnInterval: 6000,
      isTutorial: false,
    },
    {
      id: 5,
      name: 'FINAL STAND',
      duration: 30,
      subtitle: 'RANSOMWARE DEPLOYMENT — ALL SYSTEMS CRITICAL!',
      narration: 'This is it. Everything at once. Ransomware is deploying across the network. Use every tool you have. Don\'t let them win.',
      threats: ['RANSOMWARE', 'MALWARE', 'SQL_INJECTION', 'RANSOMWARE', 'DATA_EXFIL', 'BRUTE_FORCE', 'RANSOMWARE', 'PHISHING', 'RANSOMWARE'],
      spawnInterval: 3000,
      isTutorial: false,
    },
  ],

  // Rank thresholds
  RANKS: [
    { min: 0, label: 'Intern' },
    { min: 2001, label: 'Junior Analyst' },
    { min: 4001, label: 'Security Analyst' },
    { min: 6001, label: 'Security Specialist' },
    { min: 8001, label: 'Senior Analyst' },
    { min: 9501, label: 'CISO Material' },
  ],

  // Story
  STORY: {
    INTRO_LINES: [
      '11:47 PM — NovaTech Industries, Security Operations Center',
      '',
      'You are Alex Chen, junior cybersecurity analyst.',
      'First week on the job. Night shift.',
      '',
      'Your senior analyst Maya just left for a coffee break.',
      'You\'re alone in the SOC.',
      '',
      'Suddenly, the threat detection system flashes RED.',
      '',
      '>> ALERT: Coordinated attack detected',
      '>> THREAT ACTOR: PHANTOM CLAW',
      '>> TARGET: Patient medical records database',
      '>> OBJECTIVE: Data theft + ransomware deployment',
      '',
      'Maya\'s phone goes straight to voicemail.',
      '',
      'You\'re on your own.',
      '',
      '[ DEFEND THE NETWORK ]',
    ],
    WIN_LINES: [
      'ATTACK NEUTRALIZED.',
      '',
      'Maya returns, sees the logs.',
      '"You just saved 50,000 patient records."',
      '"Not bad for your first week."',
    ],
    LOSE_LINES: [
      'NETWORK COMPROMISED.',
      '',
      'The screens flash:',
      '"YOUR FILES HAVE BEEN ENCRYPTED"',
      '"PAY 50 BTC TO RECOVER"',
      '',
      'Patient data is gone.',
      'The hospital network is locked.',
    ],
  },
};
